name: BankSystem CI Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # Cấu hình Matrix chạy đa hệ điều hành
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Sử dụng biến matrix.os thay vì fix cứng ubuntu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build dự án với Maven
        run: mvn clean verify checkstyle:check
               - name: Lưu trữ báo cáo JaCoCo
               uses: actions/upload-artifact@v4
               if: always() # Dùng always() để dù build fail (do chưa đủ 80%) vẫn lấy được báo cáo xem thiếu chỗ nào
               with:
                 name: jacoco-report-${{ matrix.os }}
                 path: target/site/jacoco/

      - name: Lưu trữ file JAR
        uses: actions/upload-artifact@v4
        if: success()
        with:
          # Đổi tên artifact để không bị trùng lặp giữa 3 hệ điều hành
          name: bank-system-jar-${{ matrix.os }}
          path: target/*.jar